version: "3.9"

services:
  backend:
    build: ./backend
    container_name: rag_backend
    ports:
      - "8000:8000"
    environment:
      AWS_REGION: ${AWS_REGION}
      KNOWLEDGE_BASE_ID: ${KNOWLEDGE_BASE_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    
    dns:
      - 8.8.8.8
      - 8.8.4.4


    networks:
      - rag_network

  frontend:
    build: ./frontend
    container_name: rag_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
