version: "3.9"

services:
  backend:
    build: ./backend
    container_name: rag_backend
    ports:
      - "8000:8000"
    
    networks:
      - rag_network

  frontend:
    build: ./frontend
    container_name: rag_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
